/**
 * Client-side data export: CSV, Excel (SpreadsheetML) and print-to-PDF.
 * Dependency-free — files are assembled in memory and downloaded via blob.
 */

export type ExportCell = string | number | null | undefined;

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function csvEscape(cell: ExportCell): string {
  const s = cell == null ? "" : String(cell);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Downloads rows as UTF-8 CSV (BOM included so Excel detects encoding). */
export function downloadCsv(filename: string, headers: string[], rows: ExportCell[][]) {
  const lines = [headers.map(csvEscape).join(","), ...rows.map((r) => r.map(csvEscape).join(","))];
  const blob = new Blob(["﻿" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" });
  triggerDownload(blob, filename.endsWith(".csv") ? filename : `${filename}.csv`);
}

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Downloads rows as a native Excel workbook (SpreadsheetML 2003, .xls). */
export function downloadExcel(
  filename: string,
  headers: string[],
  rows: ExportCell[][],
  sheetName = "Report",
) {
  const cell = (v: ExportCell, header = false) => {
    const isNumber = typeof v === "number" && Number.isFinite(v);
    const style = header ? ' ss:StyleID="hdr"' : "";
    return `<Cell${style}><Data ss:Type="${isNumber ? "Number" : "String"}">${xmlEscape(
      v == null ? "" : String(v),
    )}</Data></Cell>`;
  };
  const row = (cells: string) => `<Row>${cells}</Row>`;

  const xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
  <Styles>
    <Style ss:ID="hdr"><Font ss:Bold="1"/><Interior ss:Color="#EEF2FF" ss:Pattern="Solid"/></Style>
  </Styles>
  <Worksheet ss:Name="${xmlEscape(sheetName)}">
    <Table>
      ${row(headers.map((h) => cell(h, true)).join(""))}
      ${rows.map((r) => row(r.map((c) => cell(c)).join(""))).join("\n      ")}
    </Table>
  </Worksheet>
</Workbook>`;

  const blob = new Blob([xml], { type: "application/vnd.ms-excel" });
  triggerDownload(blob, filename.endsWith(".xls") ? filename : `${filename}.xls`);
}

/**
 * Opens a print-optimized window with the report table — the browser's print
 * dialog produces the PDF (works everywhere, no PDF library).
 */
export function printPdf(
  title: string,
  headers: string[],
  rows: ExportCell[][],
  meta?: { subtitle?: string; brand?: string },
) {
  const w = window.open("", "_blank", "width=1024,height=720");
  if (!w) return;
  const th = headers.map((h) => `<th>${xmlEscape(h)}</th>`).join("");
  const trs = rows
    .map(
      (r) =>
        `<tr>${r
          .map((c) => `<td${typeof c === "number" ? ' class="num"' : ""}>${xmlEscape(c == null ? "" : String(c))}</td>`)
          .join("")}</tr>`,
    )
    .join("");

  w.document.write(`<!doctype html><html><head><title>${xmlEscape(title)}</title><style>
    * { box-sizing: border-box; font-family: -apple-system, "Segoe UI", Roboto, sans-serif; }
    body { margin: 32px; color: #0f172a; }
    h1 { font-size: 20px; margin: 0; }
    .sub { color: #64748b; font-size: 12px; margin: 4px 0 20px; }
    .brand { color: #1e40ff; font-weight: 700; font-size: 12px; letter-spacing: .08em; text-transform: uppercase; margin-bottom: 6px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { text-align: left; background: #eef2ff; padding: 8px 10px; border-bottom: 2px solid #c7d2fe; }
    td { padding: 7px 10px; border-bottom: 1px solid #e2e8f0; }
    td.num { text-align: right; font-variant-numeric: tabular-nums; }
    tr:nth-child(even) td { background: #f8fafc; }
    footer { margin-top: 24px; font-size: 10.5px; color: #94a3b8; }
    @media print { body { margin: 12mm; } }
  </style></head><body>
    <div class="brand">${xmlEscape(meta?.brand ?? "AeroTrack Pro")}</div>
    <h1>${xmlEscape(title)}</h1>
    <div class="sub">${xmlEscape(meta?.subtitle ?? `Generated ${new Date().toLocaleString()}`)}</div>
    <table><thead><tr>${th}</tr></thead><tbody>${trs}</tbody></table>
    <footer>Generated by AeroTrack Pro · ${new Date().toLocaleString()}</footer>
  </body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 350);
}
